
# Path to https://github.com/SirSykon/object_detection repository
OBJECT_DETECTION_REPOSITORY_FOLDER: "../object_detection/"

# Path to https://github.com/SirSykon/pytracker
PYTRACKER_REPOSITORY_FOLDER: "../pytracker/"

# Input information.
INPUT_FOLDER: "./input/TraficoOnBoard"
VIDEO_NAME: "FILE220426-093008R.TS"
FPS: 30

# Output information.
PRINT_DEBUG_INFO: false
SAVE_OUTPUT_VIDEO: false
SAVE_OUTPUT_IMAGES: true
OUTPUT_FOLDER: "./output"
TRACK_LENGTH_TO_CALCULATE_DANGER: 30

# Object detector information
BACKEND: "torch"
MODEL: "yolo"
MODEL_ORIGIN: "default"
TRANSFORMATIONS: ["None"]
CLASSES_TO_USE: [3,8]

# Tracker configuration information.
MAXIMUM_DISTANCE_TO_ASSOCIATE: 75
MAXIMUM_FRAMES_TO_SKIP: 10
VALUE_TO_USE_AS_INF: 10000

# Analysis configuration information.
DANGER_MODE: "ransac"
RANSAC_RESIDUAL_THRESHOLD: 1
RELEVANCE_THRESHOLD: 0.01
RELEVANCE_FILTER: True