
# Path to https://github.com/SirSykon/object_detection repository
OBJECT_DETECTION_REPOSITORY_FOLDER: "../object_detection/"

INPUT_FOLDER: "./input"
FRONT_VIDEO_NAME: "FILE210906-200117F.TS"
BACK_VIDEO_NAME: "FILE210906-200117R.TS"

OUTPUT_FOLDER: "./output"

# Object detector information
BACKEND: "torch"
MODEL: "yolo"
MODEL_ORIGIN: "default"
TRANSFORMATIONS: ["None"]